apiVersion: v1
kind: Service
metadata:
  name: myreactapp
  labels:
    app: myreactapp
spec:
  type: NodePort
  ports:
  - port: 3000
    name: http
    nodePort: 30080
  selector:
    app: myreactapp